<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>DoweLanCaster</AssemblyName>
    <RootNamespace>DoweLanCaster</RootNamespace>
    <Version>0.8.0</Version>
    <AssemblyVersion>0.8.0.0</AssemblyVersion>
    <FileVersion>0.8.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="System.Speech" Version="10.0.11" />
    <Resource Include="Resources\intro.png" />
    <Content Include="Resources\intro.mp4">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
